services:
  - type: web
    name: be-todo
    image:
      url: docker.io/easykp8/be-todo:02230287
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    image:
      url: docker.io/easykp8/fe-todo:02230287
    envVars:
      - key: REACT_APP_API_URL
        sync: false
