services:
  - type: web
    name: be-todo
    runtime: image
    image:
      url: docker.io/easykp8/be-todo:02230287
    envVars:
      - key: DB_HOST
        value: dpg-d7ueg39po60c73b1uoeg-a
      - key: DB_USER
        value: todo_list_jyy6_user
      - key: DB_PASSWORD
        value: 9rB6GGwu9rbW8O9yoRrNdvgn8mMxz6z7
      - key: DB_NAME
        value: todo_list_jyy6
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000

  - type: web
    name: fe-todo
    runtime: image
    image:
      url: docker.io/easykp8/fe-todo:02230287
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-uj05.onrender.com
